### ISSUE TITLE
Should DPUB ARIA landmark roles be allowed in the body?

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-aria#14]
Several DPUB ARIA roles are defined as subclassing the `landmark` role. This is notably the case of roles identifying sections/divisions of a publication (e.g. `doc-chapter`, `doc-part`, etc).

In EPUB, I think it is fairly common practice to find the corresponding `epub:type` values set to `body` elements. EPUBs are a collection of HTML documents, so if one document represents a publication division, I think it makes sense that the `body` itself carries the matching landmark semantics. Setting these on `body` was also a practice explicitly acknowledged but the [EPUB Structural Semantics Vocabulary ](https://idpf.github.io/epub-vocabs/structure/).

However, ARIA in HTML currently [disallows any role being set on the `body` element](https://www.w3.org/TR/html-aria/#body).

Starting from v4.2.0, EPUBCheck will report any `doc-*` roles set on the `body` element. If people used `epub:type` on `body`, and try to apply DPUB ARIA roles by following the [mapping guide](https://idpf.github.io/epub-guides/aria-mapping/), they will be confused.

I don't know the impact on AT of overriding the role of `body` elements; I think some ATs change their reading mode when landing on a `body`, so overriding the role could wreak havoc (which could be the reason why it is disallowed in ARIA in HTML). Testing with browsers+AT would be needed before filing any issue to ARIA in HTML.

In the mean time, maybe we could at least add a note to the SSV/DPUB-ARIA mapping document?

ping @mattgarrish @TzviyaSiegman

**Comment by mattgarrish** [comment]
Yes, it changes the body role of document to something that an AT might not know how to process.

That's one of many reasons why epub:type is a failure for AT, as it was never properly mapped.

The guidance not to put roles on body is already documented here: https://idpf.github.io/epub-guides/epub-aria-authoring/#sec-body

**Comment by rdeltour** [comment]
> The guidance not to put roles on body is already documented here: https://idpf.github.io/epub-guides/epub-aria-authoring/#sec-body

Oh, excellent. I missed that document!

**Comment by mattgarrish** [comment]
Maybe we should merge it with the mapping document. Too many things to find.

**Comment by rdeltour** [comment]
> Maybe we should merge it with the mapping document

👍. Both documents are pretty short and have the same objective (ease the epub:type to ARIA role transition), so it makes a lot of sense!
