### ISSUE TITLE
Example documents?

### ISSUE THREAD

**Issue by matatk** [w3c/dpub-aria#2]
I maintain a [browser extension that helps people navigate landmark regions](https://github.com/matatk/landmarks) and have recently been [working on support for the DPUB roles](https://github.com/matatk/landmarks/issues/148). I was wondering if you are aware of any publicly-available documents using these roles that I can use to test/demonstrate the extension's support for them? (I've had a look around, but not found anything; sorry if I've missed something that's already out there.)

**Comment by mattgarrish** [comment]
The best I know of that falls under freely available is the EPUB 3.1 sample of Moby Dick:
https://github.com/IDPF/epub3-samples/tree/master/31/moby-dick-mo/EPUB

It doesn't have an extensive set of landmarks, but you could merge some of the front and body matter into a single-file publication.

We created a test document that was essentially just a compilation of the examples in the specification, but I can't seem to find it. It's something we should look at providing, though. If I can find a minute, I'll see if there's something more varied on gutenberg we can enhance.

**Comment by matatk** [comment]
Thanks for your reply and the pointer to Moby Dick. I did [make a very contrived example for Landmarks' test suite](https://github.com/matatk/landmarks/blob/master/test/fixtures/digital-publishing-roles.html) but it doesn't (yet) use any roles other than the DPUB landmark roles, so it only tests that the extension picks those up. Looks like if I were to make a single file out of Moby Dick that might be an interesting (and large-scale) example.
