### ISSUE TITLE
Do not use H1 in the examples

### ISSUE THREAD

**Issue by jnurthen** [w3c/dpub-aria#26]
Throughout dpub-aria H1 is used within document sections. This seems to rely on the (unimplemented) HTML outline algorithm. We should change all usages of H1 in the examples to something more appropriate in real context so as not to imply that th e HTML outline algorithm is useful.

**Comment by mattgarrish** [comment]
No, nothing to do with the HTML algorithm, may it rest in peace. :)

It actually reflects the chunking of content that has to occur in EPUB publications. Each top-level section of a document is typically in its own separate file, so it's common for the first heading to start with an h1. The publication title doesn't appear in each file and is actually somewhat redundant even within the title page. But there's definitely no harm in making them h2s if it makes less confusion.

The heading number of the specification seems to be a bit all over the place. I'll get the numbering consistent shortly, too.

**Comment by mattgarrish** [comment]
Closing now as I've corrected the headings in https://github.com/w3c/dpub-aria/commit/aac695d73c32d169e58366591cb878da90a9ccfb
