### ISSUE TITLE
Clarify whether doc-pagebreak's name indicate the page number before or after the break?

### ISSUE THREAD

**Issue by aleventhal** [w3c/dpub-aria#27]
It's not obvious to me whether the page number assigned to a page break is for the page before or after the break. I'm guessing it's the page before, because there is no page break at the very top of the document, so there would be no way to indicate that page number.

Here's the current spec text:

						<p>A separator denoting the position before which a break occurs between two contiguous pages in
							a statically paginated version of the content.</p>
						<p>Page break locators are also commonly used to provide static markers in purely digital
							publications (i.e., where no statically paginated equivalent exists). These markers provide
							consistent navigation regardless of differences in font and screen size that can otherwise
							affect the dynamic pagination of the content.</p>
						<p>The name of the page break SHOULD be an end user-consumable page number so that assistive
							technologies can announce the page as needed (e.g., in a command to indentify the current
							page).</p>
						<aside class="example">
							<p>The following example shows three equivalent patterns for marking up page breaks in
								digital publications. Either the <code>aria-label</code> or <code>title</code>
								attributes can be used to assign the accessible name when an explicit page number is not
								provided.</p>

**Comment by aleventhal** [comment]
I'm concerned that if we don't spec this, different systems will choose differently, leading to user confusion.

**Comment by aleventhal** [comment]
@mattgarrish for word processing documents, are you suggesting maybe a hidden role=doc-pagebreak at the very start that can house the page number?

It probably doesn't matter too much right now, but if screen readers implement a "where am i" feature, I'm not sure what they would read for the first page in absence of a page number.

Either way, I think we should at least clarify the spec that the page number represents the upcoming page. Can we do that for 1.1?

**Comment by mattgarrish** [comment]
> for word processing documents, are you suggesting maybe a hidden role=doc-pagebreak at the very start that can house the page number?

Right, they're commonly not visible content in EPUB publications, either, so worst case you can have the marker for reference. I don't recall seeing a book that immediately started with a page break marker for page 1, but it would be the same suggestion I'd have for how to do it in EPUB.

> Either way, I think we should at least clarify the spec that the page number represents the upcoming page. Can we do that for 1.1?

Yes, definitely. I'll open a pull request tomorrow to clarify this.
