### ISSUE TITLE
Fix prose description for where doc-footnote is allowed

### ISSUE THREAD

**Issue by mattgarrish** [w3c/dpub-aria#38]
The text for doc-footnote says it is only for use outside of doc-endnotes, but that was true prior to deprecating doc-endnote.

It should be updated to allow anywhere, but note to see the doc-endnotes role for lists of notes.

**Comment by joanmarie** [comment]
Related to this, I think some additional clarification in Example 15 is also called for. That a `doc-footnote` lives inside a `listitem` (née `doc-endnote`) might imply that a `listitem` that lives inside a `doc-endnotes` section is still somehow "special".  My understanding is that it is not special.

Either way, some commentary about why there are `doc-footnotes` there, and if they have to be there, might be helpful.

**Comment by aleventhal** [comment]
Here's the proposed change for Chromium:
https://chromium-review.googlesource.com/c/chromium/src/+/3069120
"Remap list items inside endnote or bibliography sections"

**Comment by mattgarrish** [comment]
Closing as this was fixed with #39.
