### ISSUE TITLE
Consider a DPUB-to-PDF roles table?

### ISSUE THREAD

**Issue by cookiecrook** [w3c/dpub-aria#52]
At CSUN this year, [Paul Radius](https://www.pdfa.org/people/paul-rayius/) presented on PDF/UA and mentioned PDFA was working on a comparison table of PDF role mappings to DPUB mappings. Rather than duplicate the work, it seems like the DPUB-ARIA repo could be a good location for an informative, evergreen resource defining the expectations.

**Comment by mattgarrish** [comment]
Any thoughts on this @lrosenthol?

**Comment by lrosenthol** [comment]
Yes the PDF Association has written such a document.  I'll check on the status and provide a link.

**Comment by cookiecrook** [comment]
Overcome by:
- https://github.com/w3c/aria/issues/2070
